"""
Fixture State Model — high-level representation of what each fixture or
fixture group is doing at a given moment.

This is the contract between the lighting engine and the visualizer.
The DMX renderer can also consume these structs to generate DMX output,
keeping the rendering pipeline fixture-agnostic.

Both the live engine path and the Song Preview path (Sprint 3) produce the
same types. The visualizer consumes them without knowing the source.

Architecture overview: docs/ARCHITECTURE.md
Song Preview plan:     docs/SONG_PREVIEW_MODE.md
"""

import bisect
from dataclasses import dataclass, field
from typing import List, Optional, Tuple


# RGB color type alias for clarity
RGB = Tuple[int, int, int]


@dataclass
class UplightState:
    """State for a single RGBWAUV uplight fixture."""
    fixture_id: str
    x: float
    y: float
    color_rgb: RGB
    brightness: float      # 0.0–1.0
    active: bool = True


@dataclass
class WashState:
    """State for a wide-beam wash fixture."""
    fixture_id: str
    x: float
    y: float
    color_rgb: RGB
    brightness: float      # 0.0–1.0
    radius: float          # nominal wash radius in pixels
    pulse_strength: float  # 0.0–1.0 — expands radius on bass hits
    active: bool = True


@dataclass
class BeamState:
    """State for a narrow-beam moving-head fixture."""
    fixture_id: str
    x: float
    y: float
    color_rgb: RGB
    brightness: float      # 0.0–1.0
    angle_degrees: float   # degrees from vertical (0=up, +right, -left)
    length: float          # beam length in pixels
    spread: float          # cone half-width in degrees
    movement_speed: float  # 0.0–1.0 — how fast the beam sweeps
    active: bool = True


@dataclass
class SparkleState:
    """State for a sparkle/derby effect (e.g. GigBAR ILS derby head)."""
    fixture_id: str
    x: float
    y: float
    color_rgb: RGB
    brightness: float      # 0.0–1.0
    sparkle_amount: float  # 0.0–1.0 — density of sparkle dots
    active: bool = True


@dataclass
class ImpactState:
    """State for a strobe/impact flash fixture or channel."""
    fixture_id: str
    x: float
    y: float
    brightness: float      # 0.0–1.0
    flash_active: bool     # True when a flash pulse is currently firing
    active: bool = True


@dataclass
class RigVisualState:
    """
    Complete visual state of the rig at one moment.

    The visualizer renders from this struct; the lighting engine populates it.
    Both the live engine path and Song Preview path (Sprint 3) produce this type.
    """
    mode: str
    palette_name: str
    low_energy: float
    mid_energy: float
    high_energy: float
    overall_energy: float
    room_brightness: float
    impact_value: float
    uplights:  List[UplightState]
    washes:    List[WashState]
    beams:     List[BeamState]
    sparkles:  List[SparkleState]
    impacts:   List[ImpactState]
    blackout_active: bool
    ambient_warm: float = 0.0   # 0–1; warm W/A channel level for canvas tint


# ---------------------------------------------------------------------------
# Sprint 3: Song Preview Mode stubs
# TODO Song Preview: populate FixtureStateTimeline from DeterministicEngine
#      (see docs/SONG_PREVIEW_MODE.md → Architecture, AnalysisTimeline model)
# ---------------------------------------------------------------------------

@dataclass
class TimedFrame:
    """One RigVisualState snapshot at a specific playback time."""
    time_s: float
    state: RigVisualState


@dataclass
class FixtureStateTimeline:
    """
    Ordered sequence of timed fixture state snapshots for Song Preview Mode.

    Generated by DeterministicEngine (engine/deterministic.py — Sprint 3).
    Consumed by FixtureStateTimeline player (app/render/playback.py — Sprint 3).

    Usage (future):
        timeline = deterministic_engine.run(analysis_timeline, settings, seed)
        player   = PlaybackController(timeline)
        player.play()
        while player.is_playing:
            rig_state = player.current_state()
            visualizer.draw(screen, rig_state)
    """
    frames:          List[TimedFrame] = field(default_factory=list)
    duration_s:      float            = 0.0
    sample_rate_fps: float            = 40.0
    random_seed:     int              = 0
    settings_key:    str              = ""   # serialized SettingsSnapshot hash

    def frame_at(self, time_s: float) -> Optional[RigVisualState]:
        """Return the RigVisualState closest to the given playback time (O(log n))."""
        if not self.frames:
            return None
        times = [f.time_s for f in self.frames]
        idx   = bisect.bisect_left(times, time_s)
        if idx >= len(self.frames):
            return self.frames[-1].state
        if idx == 0:
            return self.frames[0].state
        before = self.frames[idx - 1]
        after  = self.frames[idx]
        if (time_s - before.time_s) <= (after.time_s - time_s):
            return before.state
        return after.state
